version: '3.0'
services:
  go-links:
    restart: always
    build:
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:5000:8000
    volumes:
      - "$HOME/go-links:/usr/src/app/go-links"
    
